### ISSUE TITLE
Stuck Di Check Balancer

### ISSUE THREAD

**Issue by huteri** [perlancar/perl-Finance-Bank-ID-BCA#1]
Akhir2 ini pas ngecek selalu stuck disini 

```
mech request #5 failed: after_request check error: can't find balances, maybe page layout changed?
mech request #5 failed: after_request check error: can't find balances, maybe page layout changed?
```

Itu kenapa ya? Apa BCA uda update lagi?

**Comment by perlancar** [comment]
Maaf, issue ini terlewat karena tidak ada notifikasi dari GitHub.

Sampai hari ini, skrip `download-bca` (yang menggunakan modul ini) dan juga `download-mandiri` masih lancar dipakai. Memang tanggal 17 Sep ada update. Gunakan v0.42 atau yang lebih baru.

Terima kasih.
